# Generated by Django 5.0.6 on 2024-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_alter_rector_usuario_alter_estudiante_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='rector',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='rector',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
    ]
